//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public string person_Id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<int> misses { get; set; }
        public int testlength { get; set; }
        public Nullable<double> C1 { get; set; }
        public Nullable<double> C2 { get; set; }
        public Nullable<double> C3 { get; set; }
        public Nullable<double> C4 { get; set; }
        public Nullable<double> C5 { get; set; }
        public Nullable<double> C6 { get; set; }
        public Nullable<double> C7 { get; set; }
        public Nullable<double> C8 { get; set; }
        public Nullable<double> C9 { get; set; }
        public Nullable<double> C10 { get; set; }
        public Nullable<double> C11 { get; set; }
        public Nullable<double> C12 { get; set; }
        public Nullable<double> C13 { get; set; }
        public Nullable<double> C14 { get; set; }
        public Nullable<double> C15 { get; set; }
        public Nullable<double> C16 { get; set; }
        public Nullable<double> C17 { get; set; }
        public Nullable<double> C18 { get; set; }
        public Nullable<double> C19 { get; set; }
        public Nullable<double> C20 { get; set; }
        public Nullable<double> C21 { get; set; }
        public Nullable<double> C22 { get; set; }
        public Nullable<double> C23 { get; set; }
        public Nullable<double> C24 { get; set; }
        public Nullable<double> C25 { get; set; }
        public Nullable<double> C26 { get; set; }
        public Nullable<double> C27 { get; set; }
        public Nullable<double> C28 { get; set; }
        public Nullable<double> C29 { get; set; }
        public Nullable<double> C30 { get; set; }
        public Nullable<double> C31 { get; set; }
        public Nullable<double> C32 { get; set; }
        public Nullable<double> C33 { get; set; }
        public Nullable<double> C34 { get; set; }
        public Nullable<double> C35 { get; set; }
        public Nullable<double> C36 { get; set; }
        public Nullable<double> C37 { get; set; }
        public Nullable<double> C38 { get; set; }
        public Nullable<double> C39 { get; set; }
        public Nullable<double> C40 { get; set; }
        public Nullable<double> C41 { get; set; }
        public Nullable<double> C42 { get; set; }
        public Nullable<double> C43 { get; set; }
        public Nullable<double> C44 { get; set; }
        public Nullable<double> C45 { get; set; }
        public Nullable<double> C46 { get; set; }
        public Nullable<double> C47 { get; set; }
        public Nullable<double> C48 { get; set; }
        public Nullable<double> C49 { get; set; }
        public Nullable<double> C50 { get; set; }
        public Nullable<double> C51 { get; set; }
        public Nullable<double> C52 { get; set; }
        public Nullable<double> C53 { get; set; }
        public Nullable<double> C54 { get; set; }
        public Nullable<double> C55 { get; set; }
        public Nullable<double> C56 { get; set; }
        public Nullable<double> C57 { get; set; }
        public Nullable<double> C58 { get; set; }
        public Nullable<double> C59 { get; set; }
        public Nullable<double> C60 { get; set; }
        public Nullable<double> C61 { get; set; }
        public Nullable<double> C62 { get; set; }
        public Nullable<double> C63 { get; set; }
        public Nullable<double> C64 { get; set; }
        public Nullable<double> C65 { get; set; }
        public Nullable<double> C66 { get; set; }
        public Nullable<double> C67 { get; set; }
        public Nullable<double> C68 { get; set; }
        public Nullable<double> C69 { get; set; }
        public Nullable<double> C70 { get; set; }
        public Nullable<double> C71 { get; set; }
        public Nullable<double> C72 { get; set; }
        public Nullable<double> C73 { get; set; }
        public Nullable<double> C74 { get; set; }
        public Nullable<double> C75 { get; set; }
        public Nullable<double> C76 { get; set; }
        public Nullable<double> C77 { get; set; }
        public Nullable<double> C78 { get; set; }
    }
}
